### ISSUE TITLE
Why is my antivirus thinking is as a trojan??

### ISSUE THREAD

**Issue by ItzShubhamDev** [TKMAX777/RDPRelativeInput#2]
![image](https://github.com/TKMAX777/RDPRelativeInput/assets/88220606/4377f67b-1954-416e-89a4-9c8b16abf92d)

**Comment by TKMAX777** [comment]
As a developer, I have no recollection of writing any malicious programs. Windows Defender often misidentifies unfamiliar DLLs as Trojan horse programs in its efforts to enhance system security.

If you have concerns, you can download the source code and verify its safety before compiling the program yourself. Regardless, if you wish to execute it, you’ll need to add the DLL to Windows Defender’s allowed list.

At present, I don’t know how to resolve this specific issue with Windows Defender’s behavior, so I’ll document it as a known issue in the readme.md file.

**Comment by TKMAX777** [comment]
https://github.com/TKMAX777/RDPRelativeInput/commit/e4a882d251c6781f5d922de860a74bd9b44437c3

**Comment by itzshubhamdev** [comment]
Alright thanks!
